version: "3.9"

services:
  aureus_dev:
    build:
      context: .               # apunta a la carpeta donde está el Dockerfile
      dockerfile: Dockerfile
      args:
        # opcional: tag/branch específica de Aureus
        AUREUS_REF: master
    image: aureus-dev:latest
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: https://dev-erp.tu-dominio.com

      DB_CONNECTION: pgsql
      DB_HOST: 127.0.0.1       # o la IP privada del host/servidor de DB
      DB_PORT: "5432"
      DB_DATABASE: aureus_dev
      DB_USERNAME: aureus
      DB_PASSWORD: ${DB_PASSWORD:?set_me}

      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      REDIS_CLIENT: phpredis
      REDIS_HOST: 127.0.0.1     # o IP privada del host/servidor de Redis
      REDIS_PORT: "6379"
      # REDIS_PASSWORD: ${REDIS_PASSWORD}

      AUREUS_AUTO_INSTALL: "true"
      RUN_QUEUE: "false"        # "true" si no usarás worker aparte
      RUN_SCHEDULE: "false"     # "true" si no usarás worker aparte
    volumes:
      - aureus_dev_storage:/var/www/html/code/storage
      - aureus_dev_cache:/var/www/html/code/bootstrap/cache
    ports:
      - "8081:80"               # si no vas a usar dominio/HTTPS del panel
    restart: unless-stopped

volumes:
  aureus_dev_storage:
  aureus_dev_cache:
